#cloud-config

groups:
  - ubuntu: [root,sys]
  - hashicorp

users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin

packages:
  - python3
  - python3-pip

write_files:
    - content: |
        config = {
            "db_hostname": "${db_hostname}",
            "db_user": "${db_user}",
            "db_password": "${db_password}",
            "db_name": "${db_name}"
        }
      path:
        /data/config.py
    - content: |
        from datetime import datetime, timezone
        from flask import Flask
        import psycopg2
        from config import config

        conn = psycopg2.connect(
            host=config["db_hostname"],
            user=config["db_user"],
            password=config["db_password"],
            dbname=config["db_name"],
            port=6432
        )
        cur = conn.cursor()
        conn.commit()

        cur.execute("CREATE TABLE IF NOT EXISTS visits (visit_dt timestamp)")

        app = Flask(__name__)

        @app.route("/")
        def hello():
            cur.execute("SELECT COUNT(*) FROM visits")
            total_visits = cur.fetchone()[0]
            cur.execute("INSERT INTO visits VALUES (%s)", (datetime.now(timezone.utc), ))
            conn.commit()
            return "Hello! The page was visited {} times".format(
                total_visits
            )

        @app.route("/ping")
        def ping():
            return "ping"

        app.run(host="0.0.0.0")
      path:
        /data/app_a.py

runcmd:
  - [ cat, /data/app_a.py ]
  - [ python3, -m, pip, install, flask ]
  - [ python3, -m, pip, install, psycopg2-binary ]
  - [ export, LC_ALL=C.UTF-8 ]
  - [ export, LANG=C.UTF-8 ]
  - [ nohup, python3, /data/app_a.py ]
